version: "3.9"
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7687:7687 # database connection
      - 7474:7474 # web interface
    # network_mode: host
    environment:
      NEO4J_AUTH: none # connect with no authentication
    volumes:
      - ./neo4j_data:/data:rw
  neodash:
    image: nielsdejong/neodash
    ports:
      - 8080:5005
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgres/data
    volumes:
      - ./pg_data:/var/lib/postgres/data:rw
    
  app:
    build: .
    network_mode: bridge