version: "3.9"
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7687:7687 # database connection
      - 7474:7474 # web interface
    environment:
      NEO4J_AUTH: none # connect with username "test" and password "test"
    volumes:
      - ./neo4j_data:/data:rw
  elk:
    image: sebp/elk
    ports:
      - 5601:5601 # kibana
      - 9200:9200 # elasticsearch
    volumes:
      - ./elastic_data:/var/lib/elasticsearch:rw
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml